### ISSUE TITLE
Docs don't reflect the code

### ISSUE THREAD

**Issue by mcasper** [reem/iron-test#19]
Just wanted to start off by saying I love Iron and all the associated projects, I think they're great :smile: 

I've got a couple quick questions about this repo, just to make sure I'm going insane.

The README show mock requests being built like `request::new(<http_method>, <request_target>)`, while the actual `request::new()` function looks like it needs three arguments, the third being a reader.

The other functions shown, `request::at`, `request::at_with` and all of `response`, don't seem to exist at all.

So I just wanted to confirm, is this project 'unfinished' at the moment? Or am I entirely missing something?

Once again, thank you for all the work :smile:

**Comment by reem** [comment]
This particular crate is in a bit of a rough state and I haven't had time to polish it up. If you or anyone else is interested in submitting some fixes for these issues I would be very appreciative, otherwise I will try to get to it myself sometime soon.

**Comment by mcasper** [comment]
I would be happy to submit some fixes, thanks for the response!
