### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by mcasper** [reem/iron-test#21]
How would we feel about a request API that makes the request for you, broken down by HTTP method?
Something like:
```Rust
mod request {
  pub fn get<H: Handler>(url: &str, handler: H) -> Response
  pub fn post<H: Handler>(url: &str, handler: H, data: Vec<u8>) -> Response
  // etc
}
```
It's a little more syntactic sugar than the previously outlined constructor API, but it would also DRY up end user's tests a bit more, and remove some duplicated setup patterns.

I'd being willing to implement either API, just thought of this while I was using this library to test an Iron project.

**Comment by reem** [comment]
It would likely have to be a macro, since the Request type borrows the bodies, I am happy to review or merge any nicer APIs that you can come up with, or brainstorm on the #iron IRC channel.

**Comment by reem** [comment]
@mcasper I'm still interested in further improvements, particularly around conveniences for testing the body of responses and for doing stuff like sending/testing json or other simple formats.

**Comment by reem** [comment]
If you are :)

**Comment by mcasper** [comment]
Oh I definitely am! :) I'll probably next work on getting a runnable examples directory working, and then I would agree that we should explore helper methods around those common use cases.

I haven't look into seeing if there is already something that does this, or if it would be feasible or not, but it would also be nice to have a easy way of testing Before/After middleware

**Comment by reem** [comment]
Well, an immediate idea I have for testing middleware is to provide simple test handler types that wrap a Before/AfterMiddleware in a Handler, so they can be used with the existing request mocking stuff without needing to set up a whole Chain in every test.
